apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: teamsykmelding-mock
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://teamsykmelding-mock.intern.dev.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /api/internal/is_alive
  readiness:
    path: /api/internal/is_ready
  accessPolicy:
    outbound:
      rules:
        - application: teamsykmelding-mock-backend
          namespace: teamsykmelding
          cluster: dev-gcp
  env:
    - name: MOCK_BACKEND_URL
      value: http://teamsykmelding-mock-backend